### ISSUE TITLE
dump new ideas

### ISSUE THREAD

**Issue by izgzhen** [monad-systems/hadrians-wall#16]
- collect *fingerprints* (uname + ...) for each build
- use a semi-public distributed database similar to blockchain's design to record all builds (the node list is privileged to prevent spamming, no PoW, no awards for now, but the data is not encrypted). It can't fork either, since any trusted build is valid. We just need a way to sync & merge the database and manage member nodes
- ideally, it should suppose the reproduction of important fingerprints on any node with sufficient resource. maybe build stuff in QEMU emulated environment.

**Comment by izgzhen** [comment]
@snowleopard

**Comment by snowleopard** [comment]
@izgzhen Sorry, I didn't get the distributed database idea. Is this meant for something more than testing?

**Comment by izgzhen** [comment]
> Is this meant for something more than testing?

Yes, and it is not really related to testing. I was imagining any P2P distributed KV DB. Kind of off-topic though :P

**Comment by izgzhen** [comment]
the wrapper should be intuitive to use -- the user can deploy it *over* some GHC folder and execute the usual `build.sh` as if in the original place

**Comment by izgzhen** [comment]
I will close this now this the following MVP has been implemented:

- Each build info (*brick*) is now generated by a tool provided in [Hadrian's brick](https://github.com/monad-systems/hadrians-brick). The bricks are simply put in this git repo and indexed by GitHub username. The supposed workflow is people submit & update their log through GitHub PR, after some manual inspection.
- This repo will simply be a website using the former one as a submodule, reading the logs in it and serve them nicely

**Comment by snowleopard** [comment]
Apart from the fact that Hadrian's Wall is built from stones, not bricks, I quite like the naming :-)
